enhancement init os
henglabs/gpdb pull request #14
Opened 2018-12-04 11:00 UTC by meredith620

## Here are some reminders before you submit the pull request
* init os内核参数不做其他事情
* 安装centos 依赖包 snmp. rsync

2018-12-04 11:14 UTC, weishishuo requested changes

2018-12-04 11:14 UTC, weishishuo commented on hengshi-build/util.sh
> +      ssh $line "mkdir ~/${sysbak}; if [ -f ${remoteLimitsConf} ];then cp ${remoteLimitsConf} ~${sysbak}/limits.conf.bk.`date +%s`; fi;if [ -f ${remoteSysctlConf} ];then cp ${remoteSysctlConf} ~${sys
```
~${sysbak}
```
 少个斜杠，有两个地方要改。

2018-12-05 03:29 UTC, meredith620 commented on hengshi-build/util.sh
> +      ssh $line "mkdir ~/${sysbak}; if [ -f ${remoteLimitsConf} ];then cp ${remoteLimitsConf} ~${sysbak}/limits.conf.bk.`date +%s`; fi;if [ -f ${remoteSysctlConf} ];then cp ${remoteSysctlConf} ~${sys
修正了

2018-12-05 03:46 UTC, weishishuo approved these changes

2018-12-05 03:46 UTC, merged