添加snmp支持
henglabs/gpdb pull request #3
Opened 2018-08-14 12:23 UTC by zhaohongyan133

2018-08-15 02:03 UTC, janplus requested changes

2018-08-15 02:03 UTC, janplus commented on hengshi-build/build-gpdb-for-cluster.sh
> +gp_snmp_monitor_address='127.0.0.1:162'
linux对于非root权限用户不能使用1024以下的端口，默认端口改为 1620 吧

2018-08-15 02:55 UTC, meredith620 commented on hengshi-build/install-cluster.sh
> +SNMP_MONITOR_ADDRESS="127.0.0.1:162"
最好探测下是否是集群化部署, 集群时最好不再用127.0.0.1这个默认值了, 比如不配置就提示用户必须配置这个变量. 否则因为默认值连不通就太隐蔽了.

2018-08-16 09:22 UTC, janplus requested changes
这个实现 GP 会自动选择一个服务器作为 master mirror并且会自动启动每一个 segment 的 replica 么？replica 数固定是2？

2018-08-16 09:22 UTC, janplus commented on hengshi-build/build-gpdb-for-cluster.sh
> +MIRROR_PORT_BASE=
应该有个默认值

2018-08-16 09:22 UTC, janplus commented on hengshi-build/install-cluster.sh
> +    -r mirror base port. if empty, mirror will not be installed.
应该通过开关控制，而不是用这么隐晦的空值

2018-08-16 10:34 UTC, zhaohongyan133 commented
这个安装默认本机为master节点，在命令行进行初始化的时候可以配置主节点的镜像，也可以通过参数指定segment的主机名，如果配置mirror参数就会有primary和mirror两个分片，如果没有指定mirror参数，就只有primary一个分片

2018-08-16 15:06 UTC, meredith620 commented on hengshi-build/install-cluster.sh
> +  sed -i -e "s:^REPLICATION_PORT_BASE=.*\$:REPLICATION_PORT_BASE=41000:" ${CLUSTER_CONFIG_FILE}
默认值用统一的形式吧，目前有变量的默认值，有写入${INSTALL_DIR}/sample-cluster/conf/postgresql.conf的默认值，还有这里替换时的默认值，还是统一梳理一下吧。

2018-08-17 08:12 UTC, meredith620 commented
ok
准备下文档需要的内容吧:
1. 检查master/segment -> mirror 当前配置的方式语句
1. 节点挂掉了需要什么操作
1. 想恢复节点需要什么操作

2018-08-17 08:47 UTC, janplus requested changes

2018-08-17 08:47 UTC, janplus commented on hengshi-build/install-cluster.sh
> +  sed -i -e "s:^.*MASTER_PORT=.*\$:MASTER_PORT=${MASTER_PORT}:" ${CLUSTER_CONFIG_FILE}
为么这两行不是 `s:^#MASTER_` 而是 `s:^.*MASTER_`？

2018-08-17 08:47 UTC, janplus commented on hengshi-build/install-cluster.sh
> +  if [ ${SEGMENT_NUM} -ge 2 ];then
这里改为 `-gt 1` 更直观些

2018-08-17 08:47 UTC, janplus commented on hengshi-build/install-cluster.sh
> +    -f when f is "on",mirror is on,else mirror is off
注意标点符号后的空格，文案建议改为 `-f mirror switch. when f is "on", mirror is on. default is off`

2018-08-17 08:50 UTC, zhaohongyan133 commented on hengshi-build/install-cluster.sh
> +  sed -i -e "s:^.*MASTER_PORT=.*\$:MASTER_PORT=${MASTER_PORT}:" ${CLUSTER_CONFIG_FILE}
这里有PORT_BASE和下面的MIRROR_PORT_BASE，如果 用.*这两行都会匹配到，就会把两行都替换掉

2018-08-17 08:52 UTC, janplus commented on hengshi-build/install-cluster.sh
> +  sed -i -e "s:^.*MASTER_PORT=.*\$:MASTER_PORT=${MASTER_PORT}:" ${CLUSTER_CONFIG_FILE}
我的意思是下面两行也应该用 `s:^#MASTER_` ，安全性更好

2018-08-17 09:32 UTC, zhaohongyan133 commented
@janplus .*修改为#，提高安全性，已修改完成

2018-08-17 09:34 UTC, janplus approved these changes

2018-08-17 09:35 UTC, janplus commented
Good work. 接下来按照靓仔的评论补充相关文档。

2018-08-17 09:35 UTC, merged

2018-08-17 09:35 UTC, janplus commented
另，让靓仔帮忙发布一个新 tag @zhaohongyan133 @meredith620

2018-08-17 09:53 UTC, meredith620 commented
@janplus  我测一遍流程之后就tag了