修改gphome为动态获取
henglabs/gpdb pull request #4
Opened 2018-08-20 08:31 UTC by zhaohongyan133

2018-08-20 08:42 UTC, janplus requested changes

2018-08-20 08:42 UTC, janplus commented on hengshi-build/build-gpdb-for-cluster.sh
> +    sed -i "1 s:^.*\$:GPHOME=\"\$( cd \"\$( dirname \"\${BASH_SOURCE[0]}\" )\" ;pwd )\":" ${INSTALL_DIR}/gpdb/greenplum_path.sh
bad practice. 应该在脚本前面通过命令初始化获得 `GPHOME`，在此处引用即可

2018-08-20 10:49 UTC, zhaohongyan133 commented on hengshi-build/build-gpdb-for-cluster.sh
> +    sed -i "1 s:^.*\$:GPHOME=\"\$( cd \"\$( dirname \"\${BASH_SOURCE[0]}\" )\" ;pwd )\":" ${INSTALL_DIR}/gpdb/greenplum_path.sh
这个地方获取到的是一行获取路径的脚本，不是显式的路径，由于双引号和$需要转义的问题，可读性比较差，我已将这个参数提取出来

2018-08-21 01:41 UTC, janplus requested changes

2018-08-21 01:41 UTC, janplus commented on hengshi-build/build-gpdb-for-cluster.sh
> +    GPHOME_CMD="\$( cd \"\$( dirname \"\${BASH_SOURCE[0]}\" )\" ;pwd )"
改为 `GPHOME_CMD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"` 更直观

2018-08-21 04:12 UTC, zhaohongyan133 commented on hengshi-build/build-gpdb-for-cluster.sh
> +    GPHOME_CMD="\$( cd \"\$( dirname \"\${BASH_SOURCE[0]}\" )\" ;pwd )"
我的目的输出是这个脚本：GPHOME=$( cd "$( dirname "${BASH_SOURCE[0]}" )" ;pwd )，不是确定的某一个目录，在真正运行的时候才会去获取目录，你这种写法的话获取到的是某个路径，不能动态获取

2018-08-21 05:39 UTC, janplus commented on hengshi-build/build-gpdb-for-cluster.sh
> +    GPHOME_CMD="\$( cd \"\$( dirname \"\${BASH_SOURCE[0]}\" )\" ;pwd )"
我提供的修改方案和你的源代码效果没有区别，只是提升代码可读性

2018-08-21 08:53 UTC, zhaohongyan133 commented
前面说master_hostname可以设置为任意机器，但测试发现安装脚本中有检测master_hostname是否为本机，如果不为本机会报错，如果设置的不是本机只能通过ssh方式进行远程安装

2018-08-21 08:56 UTC, janplus commented
@zhaohongyan133 好的，客户应该可以接受安装时的 ssh 登录，集群和运维任务相关可以评论到 henglabs/everest#1636

2018-08-21 08:57 UTC, janplus approved these changes

2018-08-21 08:57 UTC, merged