master hostname修改为自定义，以方便远程部署
henglabs/gpdb pull request #5
Opened 2018-08-22 06:15 UTC by zhaohongyan133

2018-08-22 06:20 UTC, janplus requested changes

2018-08-22 06:20 UTC, janplus commented on hengshi-build/install-cluster.sh
> +    -M master hostname.can not be null.
应该保留原有的默认值

2018-08-22 10:08 UTC, zhaohongyan133 commented
已将master_hostname修改为非必须参数，并将其默认值修改为localhost

2018-08-22 13:03 UTC, janplus requested changes

2018-08-22 13:03 UTC, janplus commented on hengshi-build/build-2018-08-22-02-51-21-839505319/gpdb-5.3.0.1-centos7-cluster/gpdb/bin/install-cluster.sh
> +set -e
提交错了文件

2018-08-23 02:23 UTC, zhaohongyan133 commented
已删除提交错误的文件，并重新提交正确的文件

2018-08-23 05:37 UTC, janplus requested changes

2018-08-23 05:37 UTC, janplus commented on hengshi-build/install-cluster.sh
> +    -M master hostname.default is localhost.
`default` 前的空格

2018-08-23 06:30 UTC, zhaohongyan133 commented
格式已调整

2018-08-23 07:21 UTC, janplus approved these changes

2018-08-23 07:21 UTC, merged